// <auto-generated />
namespace PersonalLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlteracaoAutor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlteracaoAutor));
        
        string IMigrationMetadata.Id
        {
            get { return "201611281817022_AlteracaoAutor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
